name: stellwerk-dev

services:
  stellwerk-frontend:
    build:
      context: ../stellwerk-frontend/
      dockerfile: ../docker/stellwerk-frontend/Dockerfile.dev
      target: final
    volumes:
      - type: bind
        source: ../stellwerk-frontend/
        target: /app/
        read_only: false
    network_mode: host
    depends_on:
      stellwerk-api:
        condition: service_started

  stellwerk-api:
    build:
      context: ../crates/
      dockerfile: ../docker/stellwerk-api/Dockerfile.dev
      target: final
    network_mode: host
    environment:
      - STELLWERK_API_CONFIG_FILE=/run/secrets/api_config
    secrets:
      - api_config
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:18
    restart: unless-stopped
    environment:
      - POSTGRES_DB_FILE=/run/secrets/postgres_db
      - POSTGRES_USER_FILE=/run/secrets/postgres_user
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgres_password
    ports:
      - "5432:5432"
    volumes:
      - ./postgres/data/dev:/var/lib/postgresql/18/data
    secrets:
      - postgres_db
      - postgres_user
      - postgres_password
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d \"$(cat /run/secrets/postgres_db)\" -U \"$(cat /run/secrets/postgres_user)\"" ]
      interval: 10s
      timeout: 5s
      retries: 5

secrets:
  postgres_db:
    file: postgres/secrets/POSTGRES_DB.dev.txt
  postgres_user:
    file: postgres/secrets/POSTGRES_USER.dev.txt
  postgres_password:
    file: postgres/secrets/POSTGRES_PASSWORD.dev.txt
  api_config:
    file: stellwerk-api/secrets/config.dev.toml
